#cloud-config

autoinstall:  
  version: 1
  locale: en_US
  
  refresh-installer:
    update: yes # Check for updated installer

  identity:
    hostname: hanze24rhmheserverc
    password: "$6$.YROGpB3QBe/9Z$oZiDMtFBzJd.Wn.HpMevTGUKxna0A6eq483NdL3UGP8HCJ7Ab6oC1U4r25BIJgfQavXyaC3CMo9ZAmB33qIJA0"
    username: rhmhendriks
  
  ssh:
    install-server: yes # Install SSH server

  user-data:
    cloud_config_modules:
      - salt_minion

    salt_minion:
      pkg_name: 'salt-minion'
      service_name: 'salt-minion'
      config_dir: '/etc/salt'
      conf:
        master: 192.168.156.89
      public_key: |
        -----BEGIN PUBLIC KEY-----
        <omitted>
        -----END PUBLIC KEY-----
        
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        <omitted>
        -----END RSA PRIVATE KEY-----

  late-commands:
    salt-call state.highstate

        
